Store DB to shared container on iOS
dreipol/multiplatform-redux-sample pull request #25
Opened 2021-01-28 16:42 UTC by Nils-Becker

2021-02-03 16:00 UTC, kaiwidmer approved these changes
👍

2021-02-04 06:24 UTC, tschuls requested changes

2021-02-04 06:24 UTC, tschuls commented on shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DriverFactory.kt
> +            .containerURLForSecurityApplicationGroupIdentifier("group.ch.dreipol.reZHycle")
Can we move this to a constant?

2021-02-04 06:24 UTC, tschuls commented on shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DriverFactory.kt
> +        val config = DatabaseConfiguration(name = "app.db",
Can we move this to a constant?

2021-02-04 06:24 UTC, tschuls commented on shared/src/iosMain/kotlin/ch/dreipol/multiplatform/reduxsample/shared/database/DriverFactory.kt
> +            basePath = groupUrl!!.path,
I assume you want the app to crash, if groupURL is null, correct? I would prefer a Excpetion with a message, to not have a forced unwrap.

2021-02-04 07:10 UTC, tschuls approved these changes
Merci

2021-02-04 07:10 UTC, merged